### ISSUE TITLE
오타

### ISSUE THREAD

**Issue by GimYoungPhil** [han41858/Angular-Development-with-TypeScript#1]
p. 657
forEach() 함수를 사용해서 배열의 항목**은** 콘솔에 출력해보자.

->

forEach() 함수를 사용해서 배열의 항목**을** 콘솔에 출력해보자.

**Comment by han41858** [comment]
'은'을 의도하고 쓴 것이 맞습니다만, '을'이 더 자연스럽네요.

좋은 지적 고맙습니다!! ㅎ
