### ISSUE TITLE
질문

### ISSUE THREAD

**Issue by GimYoungPhil** [han41858/Angular-Development-with-TypeScript#10]
p.222 `코드 4.11 ProductService 클래스`
```js
...

@Injectable()
export class ProductService {
	getProducts () : Product[] {
		return products.map(p => new Product(p.id, p.title, p.price, p.rating, p.description, p.categories));
	}

	getProductById (productId : number) : Product {
		return products.find(p => p.id === productId);
	}

	getReviewsForProduct (productId : number) : Review[] {
		return reviews
			.filter(r => r.productId === productId)
			.map(r => new Review(r.id, r.productId, new Date(r.timestamp), r.user, r.rating, r.comment));
	}
}
```

1. 위 코드에서 ProductService 클래스는 아직 HTTP를 주입하지 않으니깐  `@Injectable()` 데이코레이터는 없어도 동작하는 것이 맞나요?

2. getProductById() 메소드에서는 new Product(...) 와 같은 객체 생성 없이 리터럴 오브젝트를 리턴하고 있는데요.
제가 알기로는 `Interface 타입의 형태에 필요한 항목들로 오브젝트리터럴을 만들어서 넘길 수 있다 (p.730)` 입니다.
클래스도 마찬가지로 항목(프로퍼티)들이 맞으면 오브젝트리터럴 형태로 넘겨도 TypeScript는 에러 체크를 하지 않나요?

**Comment by han41858** [comment]
1. 맞습니다. 다른 클래스가 의존성으로 주입되지 않는 경우에는 `@Injectable()` 데코레이터가 없어도 동작합니다.
Angular CLI로 서비스를 만들 때도 기본적으로 `@Injectable()` 데코레이터가 지정되어 있으며, 이후에 의존성이 주입되는 경우에 `@Injectable()` 키워드가 없으면 동작하지 않으니 이 때만 주의하시면 됩니다.

2. 이 부분은 어떤 것을 물어보시는 지 잘 모르겠네요
이 코드에서 `getProductById()` 함수는 `products` 배열에서 원하는 항목을 찾아 반환하며,`Product[]` 배열이니 `find()`로 찾은 값도 `Product` 형태입니다. `new` 키워드로 `Product` 객체를 다시 생성하거나 오브젝트 리터럴도 사용할 수 있습니다만, 가장 간단한 형태는 `find()` 함수를 사용하는 것입니다.
TypeScript는 필수 프로퍼티가 존재하는 오브젝트라면 해당 클래스로 추론하기도 합니다.

이 부분을 물어보신 것이 아니라면 댓글 달아주세요~ㅎㅎ

**Comment by GimYoungPhil** [comment]
답변 주셔서 감사합니다.

2번 사항에서  `TypeScript는 필수 프로퍼티가 존재하는 오브젝트라면 해당 클래스로 추론하기도 합니다.` 이 부분은 저도 몰랐던 부분입니다. 인터페이스만 가능한 줄 알았습니다.

그런데 아직 궁금한 점이
ProductService의 메서드들이 참고하는 **products는 오브젝트의 배열**로 이해하고 있었습니다.  
그래서 getProducts()에서 배열 형태로 만들 때 new Product(...) 로 클래스 객체를 만드는 것으로,
그런데 getProductById() 는 그냥 find() 함수로 찾은 오브젝트 객체를 그냥 반환하는 것으로 이해했습니다.

getProducts()의 리턴 값은 [ 0: Product, 1: Product, 2: Product, ... ]
getProductById()의 리턴 값은 Object { id, title, ... }

제가 설명을 제대로 못 했네요. ;;;
다시 한번 확인 부탁 드립니다.

**Comment by han41858** [comment]
아.. `products` 배열은 오브젝트 리터럴의 배열인데 왜 `Product` 타입으로 인식하느냐를 물어보신 거군요 ㅎㅎ

이 부분은 앞서 말씀드린 대로 TypeScript의 타입 추론에 대한 내용입니다.
TypeScript에서는 사용하려는 클래스의 프로퍼티가 모두 포함되어 있다면 명시적인 클래스가 지정되어 있지 않아도 해당 클래스로 인식합니다. 덕타이핑과 비슷합니다.

http://www.typescriptlang.org/play/index.html 에서 아래 내용을 테스트해보시면 이해하는 데에 도움이 될 것 같네요.

```typescript
class Product {
    id : string;
    name : string;
}

const products = [{ id: 'test_id', name: 'test_name', amount : 300 }];

console.log(typeof products[0]); // object
console.log(products[0] instanceof Product); // false

function getProduct (name : string) : Product { 
    return products.find(p => p.name === name);
};

const findResult : Product = getProduct('test_name');
console.log(findResult); // { amount: 300, id: "test_id", name: "test_name" }
```

이 코드에서 `products` 배열은 오브젝트 리터럴로 선언했습니다.
`typeof`를 찍어보면 `object`를 출력하고, `instanceof Product`도 `false`를 반환합니다.

하지만 `Product` 클래스에 있는 `id` 프로퍼티와 `name` 프로퍼티를 모두 갖고 있기 때문에, TypeScript의 타입 추론에 의해 `Product` 클래스로 사용할 수 있습니다.
이 때, `product` 클래스에 `tax` 프로퍼티가 추가된다면, `products` 배열 안에 있는 오브젝트에 이 프로퍼티가 없기 때문에 `Product` 클래스로 추론하지 않습니다.
반면에 `products` 배열에 있는 `amount`는 `Product` 클래스에는 없지만, 이 부분은 문제가 되지 않습니다.

그래서 예제 코드의 `getProduct()` 함수가 `Product` 객체를 반환하고 `findResult` 변수가 `Product` 타입으로 선언되어 있지만, `products` 배열에서 오브젝트를 가져와서 이 변수에 할당하는 것이 문제가 되지 않습니다.

TypeScript는 명시적인 타입을 지정하는 것을 기본으로 권장하지만, 타입 추론과 같은 기능도 제공합니다.
매번 `Product` 타입으로 객체를 생성하는 것은 번거롭기 때문에 이런 방식으로 사용하기도 합니다 ^^

**Comment by GimYoungPhil** [comment]
친절하게도 코드까지 첨부해 주셔서 감사합니다.
TypeScript, ES6, ES7 내용이 쉬운듯 하면서 쉽지 않군요.

**Comment by han41858** [comment]
비슷비슷한 기능이 있기도 하고, 확실하게 알지 않으면 헷갈릴 수 있는 부분도 많죠 ㅎ
공부를 계속 해야하는 것은 개발자의 숙명인 것 같습니다 ㅠㅠ

도움이 되셨다면 다행입니다~ ㅎ
제 책을 꼼꼼하게 읽어주시는 것 같아 매우 고맙습니다^^
