### ISSUE TITLE
p.82 소스코드 문의

### ISSUE THREAD

**Issue by jinsangYoo** [han41858/Angular-Development-with-TypeScript#11]
loading에서 Hello Angular로 넘어가질 않습니다.
똑같이 했는데 왜 그런지 모르겠습니다.

패키지.json 파일에 하기와 같이 썼고
`"devDependencies": {
    "live-server" : "1.2.0",
    "typescript" : "^2.3.4"
  }`

yarn start 후 live-server가 실행되고 바로 아래 로그가 뜹니다.
GET /typescript 404 472.257 ms - 23

브라우져 로그입니다.
`Error: Fetch error: 404 Not Found
  Instantiating http://127.0.0.1:8080/typescript
  Loading typescript
  Unable to load transpiler to transpile http://127.0.0.1:8080/app/main.ts
  Instantiating http://127.0.0.1:8080/app/main.ts
  Loading app
스택 추적:
fetchFetch/<@http://127.0.0.1:8080/node_modules/systemjs/dist/system.src.js:1478:13
ZoneDelegate.prototype.invoke@http://127.0.0.1:8080/node_modules/zone.js/dist/zone.js:391:17
Zone.prototype.run@http://127.0.0.1:8080/node_modules/zone.js/dist/zone.js:141:24
scheduleResolveOrReject/<@http://127.0.0.1:8080/node_modules/zone.js/dist/zone.js:818:52
ZoneDelegate.prototype.invokeTask@http://127.0.0.1:8080/node_modules/zone.js/dist/zone.js:424:17
Zone.prototype.runTask@http://127.0.0.1:8080/node_modules/zone.js/dist/zone.js:191:28
drainMicroTaskQueue@http://127.0.0.1:8080/node_modules/zone.js/dist/zone.js:584:25
g@http://127.0.0.1:8080/node_modules/core-js/client/shim.min.js:8:10016
F/<@http://127.0.0.1:8080/node_modules/core-js/client/shim.min.js:8:10138
k@http://127.0.0.1:8080/node_modules/core-js/client/shim.min.js:8:14293`

**Comment by jinsangYoo** [comment]
헉
혹시나 싶어서 파폭이 아니라 익스폴로러 11이랑 엣지에서 해보니 되네요?
파폭에서 안되서 토시 하나도 안틀리게 하느라 시간 엄청 썼는데 ㅜㅜ

dependencies에 있는 것들을 최신 버전으로 하면 익스플로러랑 엣지에서도 안되고
책이랑 동일 버전을 사용해야만 그나마 익스플로러에서 되네요;;; 파이어 폭스는 전혀 안됨

**Comment by GimYoungPhil** [comment]
저의 경우 현재 OS X 운영체제입니다. 아래의 브라우저에서 모두 동작하네요.

크롬 58
파이어폭스 54
사파리 10.1.1

`package.json` 파일입니다.
```json
 ...

 "dependencies": {
    "@angular/common": "4.2.2",
    "@angular/compiler": "4.2.2",
    "@angular/core": "4.2.2",
    "@angular/forms": "4.2.2",
    "@angular/http": "4.2.2",
    "@angular/platform-browser": "4.2.2",
    "@angular/platform-browser-dynamic": "4.2.2",
    "@angular/router": "4.2.2",
    "bootstrap": "4.0.0-alpha.6",
    "core-js": "2.4.1",
    "rxjs": "5.4.1",
    "systemjs": "0.19.47",
    "zone.js": "0.8.12"
  },
  "devDependencies": {
    "live-server": "^1.2.0",
    "typescript": "^2.3.4"
  }
}
```

프로젝트를 github에 올려서 작업하시면 코드에 대해 공유하기 좋습니다.

**Comment by han41858** [comment]
글쎄요... 책에 있는 예제를 돌려봤는데 다음 브라우저에서 모두 동작하는 것으로 확인됩니다.

Chrome 58.0.3029.110
Microsoft Edge 40.15063.0.0
Microsoft Internet Explorer 11.413.15063.0
Firefox 54.0

브라우저에서 지원하는 JavaScript의 문법에 따라 일부 기능이 동작하지 않을 수는 있지만,
해당 예제는 TypeScript로 작성하고 ES5로 변환하는데
문제가 될만한 요소는 찾을 수가 없네요...

Firefox에서 문제가 계속 발생하나요?

**Comment by jinsangYoo** [comment]
원인 찾았습니다.
systemjs 을 타이핑하면 인텔리센스로 "systemjs" :"0.20.14"로 자동완성 해주는데요
이걸 책에 있는 "systemjs": "0.19.47" 로 해주니까 되네요
힘들다 ㅋㅋㅋ

**Comment by han41858** [comment]
@milkybboy 님이 사용하시는 인텔리센스가 너무 똑똑했던게 문제였네요 ㅎㅎㅎ

SystemJS 버전 문제는 제가 책을 처음 봤을 때 한참 헤맸던 문제였습니다.
관련 내용은 39 페이지에 있습니다만, 0.20.x 버전에서는 transpiler 항목의 값으로 'typescript'를 그대로 쓸 수 없고 'plugin-typescript'라는 형식으로 사용해야 합니다. 세부 설정도 달라지며, 말씀하신 문제는 이 부분이었던 것 같네요.

그리고 제가 테스트했던 0.20.x 버전은 Angular 의존성 주입이 동작하지 않아서, 3장부터 예제를 진행할 수 없었습니다.
SystemJS 0.19.47 버전 사용을 권장합니다.

원인을 찾아서 다행이네요^^

**Comment by jinsangYoo** [comment]
3장에서 허비할 시간을 세이브할수 있겠네요
감사합니다.
