### ISSUE TITLE
소스 코드 질문?

### ISSUE THREAD

**Issue by GimYoungPhil** [han41858/Angular-Development-with-TypeScript#12]
p.377 코드 7.15
```ts
  ...

  }, {}, equalValidator)
});
```

`}, equalValidator)` 

FormGroup 생성자의 두번째 인자에 유효성 검사기를 넣고, 세번째에 비동기 유효성 검사기를 넣는다고 설명이 있는데요. 두번째 인자로 equalValidator가 들어가야 하는 것이 아닌가요?

**Comment by han41858** [comment]
376페이지에 구현된 equalValidator() 함수는 동기처리를 하고 있으니까... 두 번째 인자로 들어가는 것이 맞습니다 ㅠㅠ

`}, equalValidator)` 로 사용해야 맞겠네요.

GitHub에 올려둔 7장 1.form_samples 폴더의 app/09_reactive-with-validation.ts 파일을 보시면 됩니다.

코드는 제대로 작성했는데 책에 오류가 있었네요...
지적 감사합니다!!
