### ISSUE TITLE
chapter 08

### ISSUE THREAD

**Issue by GimYoungPhil** [han41858/Angular-Development-with-TypeScript#13]
p.404 ~ 407 `hello_server.ts`, `hello_server.js`

책에서는 파일명이 위와 같고 실제 코드에서는  `hello-server.ts`, `hello-server.js`와 같이 되어 있네요.
파일을 작성하거나 실행하는 데에는  큰 어려움은 없으나 알려드립니다.

**Comment by han41858** [comment]
음... 이런 문제도 있네요

항상 좋은 지적 감사드립니다!! ㅎ
