### ISSUE TITLE
문의?

### ISSUE THREAD

**Issue by GimYoungPhil** [han41858/Angular-Development-with-TypeScript#14]
p. 419  `package.json`

```json
  ...

  "devDependencies": {
    "@types/es6-shim": "^4.0.35",
    "@types/node": "^7.0.18",
    "@types/ws": "^0.0.41",
    "nodemon": "^1.11.0"
  }
}
```
책과 소스코드가 다름점 알려 드립니다.  `"@types/es6-shim": "^4.0.35",` 소스코드에는 없는데 책에는 추가 되어있습니다. 실행에는 없어도 상관 없는것 같습니다.

**Comment by han41858** [comment]
@types/es6-shim 패키지는 원서에는 있었지만, TypeScript 내부 라이브러리를 사용할 수 있기 때문에  굳이 설치할 필요가 없다고 판단하고 제 책에서는 뺐던 내용입니다.

말씀해주신 것과 같이 소스 코드는 확인해서 모두 뺐는데 책에는 반영이 안된 부분이 있었네요.
이 패키지는 설치하지 않는 것이 좋습니다.

확인 감사합니다!! ㅎ
