### ISSUE TITLE
문의

### ISSUE THREAD

**Issue by GimYoungPhil** [han41858/Angular-Development-with-TypeScript#15]
p.440 `simple-websocket-server.ts`

```ts
...

// HTTP Server
app.get('/', (req, res) => {
	res.sendFile(path.resolve(__dirname, '..', 'client/simple-websocket-client.html'));
});

...
```

소스코드에서는 `path.resolve`로, 책에서는 `path.join`로 다릅니다. 역시 실행에는 이상 없네요.

**Comment by han41858** [comment]
Node.js에 있는 `path.resolve()` 함수와 `path.join()` 함수는 기능이 비슷하지만 약간 다릅니다.

`path.join()`은 문자열을 단순하게 합치기 때문에 `[].join('/')`과 비슷하지만 `path.resolve()`는 . 이나 .. 과 같은 경로는 적절하게 생략합니다. 따라서 `/root/a/b` 위치에서 `path.join(__dirname, '..', 'c');` 를 실행하면 `/root/a/b/../c` 가 되지만 `path.resolve(__dirname, '..', 'c');` 를 실행하면 `/root/a/c`가 됩니다.
개인적으로는 `path.resolve()`를 사용하는 것이 더 좋다고 생각합니다.

이 부분도 #14 이슈와 비슷하게 원서에서는 `path.join()`을 사용했지만 `path.resolve()`를 사용하는 것이 더 낫다고 생각해서 모두 `path.resolve()`로 바꿨습니다. 440 페이지에 있는 코드에는 반영이 안되었네요..

알려주셔서 감사합니다 ㅎㅎ
