### ISSUE TITLE
문의?

### ISSUE THREAD

**Issue by GimYoungPhil** [han41858/Angular-Development-with-TypeScript#16]
p.445 `custom-observable.service.ts`

```ts
import { Observable } from 'rxjs/Rx';

...
```

위의 방식으로 하면 rxjs 전체 파일을 로드하게 되는것이 맞나요? ><

다른 파일들에서는 아래와 같이 모듈을 설정 하였습니다.

`import { Observable } from 'rxjs/Observable';`

**Comment by han41858** [comment]
`'rxjs/Rx'` 을 `import`하면 RxJS 패키지의 `Rx.js` 파일을 참조하는데, 이 파일은 RxJS 패키지의 인덱스 파일이며, RxJS 파일의 모든 라이브러리를 로드합니다. 따라서 이 방식으로 `Observable`을 참조하면 RxJS 패키지를 전부 로드합니다.

반면에 `'rxjs/Observable'`을 `import`하면 RxJS 패키지의 `Observable` 모듈만 로드하고, 이 모듈에서 `Observable` 객체를 참조합니다.


RxJS의 패키지 중 어디에 Observable이 선언되어 있는지 찾기 귀찮다면 'rxjs/Rx'를 그대로 사용하는 방법도 있습니다.

두가지 방법 모두 `Observable`을 사용하는 데에는 문제가 없지만, 필요한 패키지만 로드하는 것이 간결하기 때문에, 'rxjs/Observable' 패키지에서 Observable을 참조하는 것을 추천합니다.

그리고 사용하지 않는 모듈을 모두 불러오면서, 각 모듈에 있는 내용을 실행하기 때문에 성능 면에서도 좋지 않을 것이라고 생각됩니다만... 이 내용은 확인을 좀 해봐야겠네요 ㅎ
