### ISSUE TITLE
chapter08 실습 코드 질문?

### ISSUE THREAD

**Issue by GimYoungPhil** [han41858/Angular-Development-with-TypeScript#17]
책에는 없는 내용입니다만,

`0.auction/client/app/components/product-detail/product-detail.component.ts`

위의 실습 코드를 보면 ProductDetailComponent 클래스를 선언하고 있습니다. 

```ts
    private subscription: Subscription = null;
``` 

위와 같이 클래스에서 변수를 선언하는데 `Subscription` 타입이 참조가 없습니다.
다음과 같이 참조 타입을모듈 선언하는 방식이 맞는 건가요?

`import { Subscription } from 'rxjs/Subscription';`

**Comment by han41858** [comment]
`Subscription` 객체에 대한 참조가 빠져있네요.. 말씀하신 것처럼 'rxjx/Subscription'에서 참조하는 것이 맞습니다.
