### ISSUE TITLE
chapter 9.3.4 컴포넌트 테스트 : 오타

### ISSUE THREAD

**Issue by GimYoungPhil** [han41858/Angular-Development-with-TypeScript#21]
p.510

`코드 9.9 weather.spec.ts`
->
`코드 9.9 weather.component.spec.ts`

component 이 추가되는 것이 맞나요?

**Comment by han41858** [comment]
네~ component를 붙이는 것이 맞습니다.

파일 이름은 weather.component.spec.ts가 되어야 합니다.

알려주셔서 감사합니다!! ㅎ
