### ISSUE TITLE
chapter 10.2 질문

### ISSUE THREAD

**Issue by GimYoungPhil** [han41858/Angular-Development-with-TypeScript#22]
p.559 `코드 10.9 vendor.ts`

```ts
import '@angular/platform-browser';
```
위에 `@angular/platform-browser` 를 포함 하지 않는 이유가 있나요?

**Comment by han41858** [comment]
오타이기 때문입니다... ㅠㅠ
경매 소스에는 추가해놨는데 앞쪽에 빠졌네요..

`@angular/platform-browser`도 추가하는 것이 맞습니다!!

고맙습니다 ㅎ
