### ISSUE TITLE
styleUrl 과 styleUrls 차이

### ISSUE THREAD

**Issue by taegyunum** [han41858/Angular-Development-with-TypeScript#25]
안녕하세요. 

출판하신 책 내용으로 Angular의 내용을 잘 습득하고 있습니다.
이해하기 좋게 잘 작성된 책 입니다.

Chp3의 실전 예제의 
/app/components/home/home.component.ts
파일에 대해 책에선 
styleUrls : ['/home.css'], 

로 표기되어 있고 github의 예제 소스코드는
styleUrl : 'app/components/home/home.component.css', 
로 표기되어있어 혼동의 여지가 있다고 생각합니다.

또한 다른 예제들에선 외부 css를 연결하는 경우 styleUrls : ['경로'] 와 같은 방식을 사용하는데

styleUrl : '경로' 와 styleUrls : ['경로'] 은 단순히 한개를 지정하는지 여러개를 지정할 수 있는지의 차이만 있는지 궁금합니다.

**Comment by han41858** [comment]
공부하는 데에 도움이 된다니 다행입니다 ㅎㅎ

`styleUrls`와 관련해서 오류가 있었습니다.... ㅠㅠ
Angular에서는 스타일을 지정할 때 `styles : []`를 사용하거나, 외부 스타일 파일을 지정할 때 `styleUrls : []`를 사용해서 **배열 형태로만** 사용해야 합니다.

Angular CLI를 사용하는 환경에서 `styleUrl`을 사용하면 알 수 없는 항목이 사용되었다고 에러를 발생시키는데, SystemJS를 사용하는 환경에서는 이 에러를 감지하지 못해서 오류를 인지하지 못했습니다...
SystemJS 환경에서 `styleUrl`을 사용하면 에러는 발생하지 않지만 실제 파일을 내려받지 않기 때문에, 사용하지도 않습니다. 이 내용은 Chrome 개발자 도구에서 네트워크 탭을 보면 확인할 수 있습니다.

### `styleUrl`은 사용할 수 없습니다. `styleUrls`를 사용해야 합니다.


못보고 지나쳤던 문제가 있어서 혼란스럽게 했네요... 죄송합니다 ㅠㅠ
좋은 지적 해주셔서 고맙습니다!!
