### ISSUE TITLE
chp4 197p 오탈자

### ISSUE THREAD

**Issue by taegyunum** [han41858/Angular-Development-with-TypeScript#28]
책에는 코드 4.4 옆에 main.ts로 표시되어있으나
main-change-provider.ts로 표기되는 것이 맞을 것으로 생각됩니다.

사소한 부분일 수 있으나 추후 책이 더 나은 버전으로 개정될 때 작은 보탬이 되고자 남깁니다.

**Comment by han41858** [comment]
본문에는 main-change-provider.ts라는 설명이 있었네요!! 잘못된 부분이 맞습니다 ㅠㅠ

알려주셔서 감사합니다 ㅎ
