### ISSUE TITLE
appendix A 오류?

### ISSUE THREAD

**Issue by GimYoungPhil** [han41858/Angular-Development-with-TypeScript#29]
p. 653 가장 아래 코드

```js
let { sym, price, stockExchange } = getStock();
console.log(`The price of ${symbol} is ${price} ${stockExchange}`);
```

위 코드가 아래와 같이 변경 되어야 맞나요?

```js
let { symbol: sym, price, stockExchange } = getStock();
console.log(`The price of ${sym} is ${price} ${stockExchange}`);
```

**Comment by han41858** [comment]
객체를 분해할 때 사용하는 alias에 대한 내용인데,
오타가 있네요... ㅠㅠ

말씀하신 대로 `symbol : sym`로 사용하는 것이 맞습니다.

알려주셔서 감사합니다 ㅎ

**Comment by GimYoungPhil** [comment]
그렇다면 아래 콘솔 출력도 변경되어야 겠네요. ㅎㅎ

`${symbol}` -> `${sym}`

**Comment by han41858** [comment]
옙~~ 맞습니다 ㅎㅎㅎㅎ

**Comment by han41858** [comment]
책은 거의 다 보신건가요? ㅎ

굉장히 꼼꼼히 보신 것 같아서 책에 대한 의견을 좀 듣고 싶습니다 ㅎㅎ
han41858@gmail.com으로 연락 주실 수 있나요~?

**Comment by GimYoungPhil** [comment]
아 오류 수정이 잘 못 되었습니다. p.652 - p.653 위의 코드와 함께 수정되어야 할것 같아요 ㅎㅎ

의견은 메일로 드리겠습니다.

**Comment by han41858** [comment]
객체 분해가 제대로 이루어지지 않은 경우는 `undefined`가 표시되는게 맞는데,
이때 653페이지를 기준으로 첫 번째 실행결과에 `sym`이 `undefined`로 표시되고,
마지막 실행 결과에 `stockExchange`가 `undefined`로 표시되는 것이 맞습니다 ㅎ

p.652, p.653의 다른 코드는 문제가 없는데, 어떤 부분을 말씀하시는 건가요?

**Comment by GimYoungPhil** [comment]
> let { symbol: sym, price, stockExchange } = getStock();
> console.log(`The price of ${sym} is ${price} ${stockExchange}`);

위 코드를 실행하면 결과는 예상한 대로 다음과 같다.

> The price of IBM is 100 undefined

아래 코드 결과 설명에서는 stockExchange 만 undefined로 표시 되어야 한다고 했는데요.
README.md 파일에서 오류설명 테이블이 이상한것 같아요.

653 | 16 | 
**652** | 17 | 

->

653 | 16 | 
**653** | 17 |

죄송합니다. 자꾸 사소한 것에 꼬투리 잡아서요.;;;

**Comment by han41858** [comment]
> The price of IBM is 100 undefined

위와 같은 결과를 내기 위해 작성해본 테스트 코드는 다음과 같습니다

```html
<html>
	<head>
		<script>
			function getStock (){
				return {
					symbol : 'IBM',
					price: 100.00
				};
			}

			let { symbol : sym, price, stockExchange } = getStock();
			console.log(`The price of ${sym} is ${price} ${stockExchange}`);
		</script>
	</head>
</html>
```
코드에는 문제가 없습니다만... 수정한 페이지가 잘못되었네요 ㅠㅠ

**Comment by han41858** [comment]
같은 부분을 본 게 맞네요 ㅎㅎ
알려주셔서 감사합니다!! ㅎㅎㅎ

제 메일로 메일 주시면 다시 연락드리겠습니다!! ㅎ
