### ISSUE TITLE
오타 제보

### ISSUE THREAD

**Issue by wellstyle** [han41858/Angular-Development-with-TypeScript#31]
15페이지 
> 예제 코드와 코드에 대한 설명은 최대한 단순하게 작성했지만, 이해하기 어렵지 않을 것이다.

이 문장을
> ...단순하게 작성했기 때문에, 이해하기 어렵지 않을 것이다.

정도로 수정하면 문맥이 자연스러울 것 같습니다.

**Comment by han41858** [comment]
해당 부분은 "코드에 대한 설명은 최대한 단순하게 작성했음에도 불구하고, 이해하기 어렵지 않다"는 의미로 작성했습니다.
이해하기 쉽게 하려고 설명을 의도적으로 간단하게 작성하게 한 것은 아닙니다 ㅎㅎ

한 번 더 생각해보게 되었네요 ㅎ
고맙습니다!!

**Comment by wellstyle** [comment]
아.. 그런 의도로 쓰신거군요. 저도 뒷부분을 읽다보니 이해되네요.
생략한 코드가 있지만 이해하기 어렵지 않다는 의미겠네요~

**Comment by han41858** [comment]
옙!! 맞습니다 ㅎ
