### ISSUE TITLE
chapter 10.2 질문?

### ISSUE THREAD

**Issue by GimYoungPhil** [han41858/Angular-Development-with-TypeScript#32]
p.559 코드 10.9 vendor.ts
p.563 코드 10.12 package.json

위의 두 코드와 관련해서 질문드립니다.

1.
`@angular/platform-browser-dynamic` 모듈이 `@angular/compiler`모듈을 의존하고 있네요. 모르고 삭제했더니 번들과정에서 에러가 발생하네요.
코드 10.9 vendor.ts 에 `import '@angular/compiler';` 과 같이 포함 시키지 않는 이유가 있을까요?

2.
SystemJS 로 모듈을 설정할 때는 core-js를 사용했는데 webpack 환경에서는 `import 'reflect-metadata/Reflect.js';`로 대체 된 것으로 보면 맞나요?

**Comment by han41858** [comment]
1.
확인을 좀 해봐야 하는 내용이네요.

1-1. 삭제하셨다는 게 vendor.ts 파일에서 `import '@angular/platform-browser-dynamic';` 부분을 지웠다는 말씀이신가요?
1-2. 번들링은 `yarn build`로 하셨나요?

2.
core-js 패키지는 JavaScript 폴리필 패키지입니다.
자세한 내용은 https://github.com/zloirock/core-js/blob/master/README.md 에서 확인하실 수 있으며,
브라우저에서 Array.fill()이나 find()와 같은 함수를 지원하지 않을 때 이 함수를 사용할 수 있게 하는 패키지입니다.
다시 확인해보니 ES6뿐 아니라 ES7의 일부 기능도 지원하고 있는 것으로 보이네요.

그리고 reflect-metadata 패키지는 .js 코드에 데코레이터를 사용할 수 있게 하는 패키지이며,
`@Component`나 `@Module`과 같은 어노테이션을 지원하는 패키지입니다.

말씀하신 core-js 패키지와 reflect-metadata 패키지는 용도가 다릅니다.

책의 앞부분에서는 core-js 패키지를 사용했지만, TypeScript 컴파일 옵션에서 `compilerOptions.lib` 항목의 값을 `["es2015", "dom"]`로 지정하면 core-js 패키지를 사용하지 않아도 문제가 없어서 이 패키지는 이후에 사용하지 않았습니다.
다만, 이 내용은 tsconfig.json 파일을 작성하거나 SystemJS에 컴파일 옵션으로 설정해야 하기 때문에, 이 부분이 더 번거롭다고 생각한 경우에는 core-js를 그냥 사용하기도 했습니다.


1번에 대해서 추가 정보를 주시면 좀 더 확인해보겠습니다^^

**Comment by GimYoungPhil** [comment]
1. `yarn remove @angular/compiler` 를 이용해서 지웠다는 뜻 입니다. 삭제 후 번들 과정에서 에러가 나와서 다시 추가 시켰습니다. 
그런데 코드 10.9 vendor.ts 에 `import '@angular/compiler';` 과 같이 포함 시키지 않는 이유가 궁금합니다.

2. 질문을 드린 이유는 p.37~38 에서 core-js가 클래스 데코레이터를 사용하기 위해서 라고 책에 나와서 입니다.
   그러면 SystemJS를 사용할 때는 어노테이션을 위해서 reflect-metadata를 설치하지 않은 이유는 무엇인가요?

**Comment by han41858** [comment]
1. `vendor.ts` 파일에 @angular/compiler를 추가하지 않더라도 이 패키지는 `@angular/platform-browser-module` 패키지에서 사용하기 때문에, `vendor.ts` 파일에 자동으로 포함됩니다. Webpack은 의존성이 있는 모듈을 따라가며 번들링하기 때문입니다.
다만, `@angular/compiler`를 명시적으로 추가하는 경우에는 번들링 결과물이 약간 달라지는데, 명시적으로 지정한 것에 대한 차이라고 생각됩니다.
원래 `vendor.ts` 파일의 역할은 애플리케이션에서 사용하는 라이브러리를 다른 파일로 뽑아내기 위한 것이며, `@angular/compiler`는 애플리케이션에서 명시적으로 사용하지 않기 때문에 vendor.ts 파일에도 추가하지 않는 것이 좋을 것 같습니다.

2. 데코레이터를 사용하지 않는 한 core-js 는 일반적으로 ES6 폴리필로 사용합니다.
하지만 패키지 설명 중 https://github.com/zloirock/core-js/blob/master/README.md#pre-stage-0-proposals 부분을 보시면 core-js 패키지에서도 데코레이터를 사용하는 메타데이터 문법을 지원하고 있습니다.
단순하게 보면 reflect-metadata보다 core-js가 커버하는 범위가 넓다고 보시면 될 것 같고....
폴리필을 설정하는 방법이 여러가지가 있는데, 패키지들이 복잡하게 얽혀있긴 하네요...ㅎ;;

**Comment by GimYoungPhil** [comment]
자세하게 설명해 주셔서 감사합니다.
제가 미리 패키지 하나하나 살펴봐야 하는것을 귀찮게 해드렸네요.
감사합니다.

**Comment by han41858** [comment]
별말씀을요 ㅎ
덕분에 저도 다시 한 번 찾아봤습니다~~ㅎㅎ

고맙습니다 ㅎㅎㅎ
