### ISSUE TITLE
Chp5 실습예제 질문

### ISSUE THREAD

**Issue by taegyunum** [han41858/Angular-Development-with-TypeScript#33]
안녕하세요

Chp5의 실습예제에서

home.components.ts 파일에

import { FilterPipe } from '../pipes/filter.pipe';

를 포함하지 않아도 프로그램이 정상적으로 작동하는 것을 확인했습니다.

그 이유가 app.module.ts에 포함되어 프로그램 전체적으로 해당 파이프가 불러와지기 때문인가요?

반대로 home.components.ts에만 해당 import 구문을 넣고 app.module.ts에서 제외했을 경우엔 오류가 발생함을 확인할 수 있었습니다.

그렇다면 파이프는 app.module.ts에서만 불러와야하는지 문의드립니다.

**Comment by han41858** [comment]
답변이 늦어 죄송합니다.

우선, 말씀하신 대로 home.component.ts 파일에서 FilterPipe를 임포트하는 부분은 필요 없으니 이 부분은 삭제하는 것이 좋을 것 같습니다.
FilterPipe는 `@NgModule` 어노테이션의 `declarations` 항목에 등록했기 때문에 모듈 안에서 사용할 수 있습니다.

FilterPipe는 예제에서 만든 커스텀 컴포넌트이기 때문에 `declarations`에 이 컴포넌트를 등록해야 하는데, `declarations` 항목은 `@Component`에는 없고 `@NgModule`에 있는 항목입니다. 따라서 컴포넌트에 단독으로 사용할 수는 없고, 상위 모듈에 등록해서 사용해야 합니다.

`@Component`에 `declarations` 항목을 선언하면 다음과 같은 에러가 표시됩니다.
> TS2345: (생략) and 'declarations' does not exist in type 'Component'
