### ISSUE TITLE
오타 제보

### ISSUE THREAD

**Issue by csj4032** [han41858/Angular-Development-with-TypeScript#36]
p. 66
map 설명 3번째 줄 코드

System.import('./es6module.js');  // GET /es6Module.js
>> System.import('./es6module.js');  // GET /es6module.js

es6Module.js >> es6module.js 대문자가 들어갔네요

**Comment by han41858** [comment]
맞습니다!! 해당 부분은 파일의 경로를 명시한 것이기 때문에

주석이 // GET /es6module.js가 되어야 맞습니다

알려주셔서 고맙습니다^^
