### ISSUE TITLE
내용문의

### ISSUE THREAD

**Issue by csj4032** [han41858/Angular-Development-with-TypeScript#37]
p.99 'stats 배열에 들어있는 항목이 false면 별을 색칠하지 않고, true면 별을 색칠한다.'
반대 아닌가요 false 칠하고 true 칠하지 않고 (p.100 코드 2.23 설명 내용 및 p.101 그림 2.6 참고 해봤습니다.)

**Comment by han41858** [comment]
이 부분은 저도 보면서 헷갈렸던 부분인데... 오류가 맞네요 ㅠㅠ

이 예제에서는 Bootstrap의 glyphicon(http://getbootstrap.com/components/#glyphicons) 중에서
`glyphicon-star`와 `glyphicon-star-empty`를 사용하고 있으며,
코드 2.23을 기준으로 `glyphicon-star`는 기본으로 지정하고, star값이 true라면 `glyphicon-star-empty`를 추가로 지정합니다.

따라서 star값이 true일 때 색칠되지 않은 값이 표시되는 것이 맞습니다.

말씀하신 내용이 맞습니다 ㅠㅠ

알려주셔서 고맙습니다!!
