### ISSUE TITLE
오타 제보(?)

### ISSUE THREAD

**Issue by csj4032** [han41858/Angular-Development-with-TypeScript#38]
p.185
왜냐하면 TypeScript 컴파일러 옵션에 emitDecoratorMetaData 값을 >>
왜냐하면 TypeScript 컴파일러 옵션에 emitDecoratorMetadata 값을
p.186 에는 emitDecoratorMetadata 표기 했습니다.
혹시나 해서 https://www.typescriptlang.org/docs/handbook/compiler-options.html 참고 했습니다.

**Comment by han41858** [comment]
넵 맞습니다!!

Metadata에서 d는 소문자가 맞습니다 ㅠㅠ

알려주셔서 고맙습니다 ㅎ
