### ISSUE TITLE
궁금한 사항 질문입니다.

### ISSUE THREAD

**Issue by GimYoungPhil** [han41858/Angular-Development-with-TypeScript#4]
p.85 

> yarn add -D bootstrap
> yarn add -D jquery

bootstrap, jquery는 -D 옵션을 빼고 설치하는 것이 의미에 맞지 않나요?
소스 코드의 `package.json`를 보면 dependencies의 항목에 추가 되어 있어서 궁금해서 질문 드립니다.

**Comment by han41858** [comment]
오류네요 ㅠㅠ

Webpack을 사용하기 전이니 일반 의존성으로 설치하는 것이 맞습니다.

제대로 지적해주셔서 고맙습니다!!
