### ISSUE TITLE
오타제보

### ISSUE THREAD

**Issue by cheooool** [han41858/Angular-Development-with-TypeScript#41]
p.316 10번째 줄 "on-changes-with-param.ts 파일로 작성"이라고 되어 있는데

하단 코드 6.10 파일명은 ng-onchanges-with-param.ts으로 잘못나와있네요.

**Comment by han41858** [comment]
아... 오류가 맞습니다.

실제 파일을 기준으로 on-changes-with-param.ts 파일이 맞습니다.

알려주셔서 고맙습니다!! ㅎ
