### ISSUE TITLE
오타인지 문의

### ISSUE THREAD

**Issue by cosemara** [han41858/Angular-Development-with-TypeScript#44]
360페이지 4번째  줄
템플릿 기반 폼에서는 모델 클래스에 접근할 수 없었지만,  반응형 폼에서는 반대로 템플릿에서 모델에 접근할 수 없다.

이해력이 부족한건지 오타인건가요?

**Comment by han41858** [comment]
안녕하세요. 한장현입니다.

해당 문장은 컴포넌트 클래스 입장에서 설명하는 내용입니다.

템플릿 기반 폼은 템플릿에 데이터 모델을 정의하고 `submit` 동작이 있을 때 컴포넌트 클래스로 값을 전달하는 방식을 사용할 수 있는데, 이 방식에서는 `submit` 동작 전에 컴포넌트 클래스에서 템플릿에 있는 데이터 모델에 접근할 수 없습니다.

그리고 반응형 폼에서는 컴포넌트 클래스에 데이터 모델을 정의하고 템플릿에 연결하기 때문에, 템플릿 안에서는 데이터 모델에 필드를 추가할 수 없습니다.

데이터 모델에 접근하는 방법이 다르기 때문에 폼 유효성을 검사하는 방식도 약간 다릅니다.

컴포넌트 클래스 입장이라는 설명이 부족했네요.


그런데 조금 덧붙이자면,

템플릿 기반 폼을 쓰면서 `ngModel` 디렉티브(책에서 사용한 ngModel은 템플릿 폼 변수입니다.)로 양방향 바인딩하면 컴포넌트 클래스에서 데이터 모델에 접근할 수 없는 것만은 아닙니다.
`[ngModelOptions]="{standalone: true}"` 와 같은 옵션을 더 줘야하긴 하지만요 ㅎ

**Comment by cosemara** [comment]
예 알겠습니다.
감사합니다.
