### ISSUE TITLE
Chapter08 소스 문의

### ISSUE THREAD

**Issue by cosemara** [han41858/Angular-Development-with-TypeScript#45]
실습하다보니 기능이 동작하지 않는 부분이 있어 확인 문의드립니다.

chapter08 > 8.5 실습
1. 화면에서 Default로 최초 검색시에는 전체 검색이 됨
2. 카테고리를 book으로 선택하여 검색 후, 다시 All Categories로 선택하여 검색하면 결과 없음.

chapter08/0.auction/client/app/services/product.service.ts
위 파일에 객체를 쿼리스트링으로 변환하는 함수에 category를 변환하는 부분
if (params.category !== -1) {...}  --> 비정상 동작
if (params.category != -1) {...}  --> 정상 동작

쿼리가 문자열로 오는 것 같은데 그래서 안되는 것 같습니다. 

확인부탁드립니다.

**Comment by han41858** [comment]
그러네요!!

search.component.html 에서 `<select>` 안에 사용한 `<option value="-1">` 부분은 value를 문자열로 지정하는 구문이었는데,
이 값을 다른쪽에서 숫자로 보고 있어서 오류가 났습니다..

확인해서 코드 수정했습니다.

불편을 드려 죄송합니다.
알려주셔서 고맙습니다^^

**Comment by cosemara** [comment]
네 감사합니다.
