### ISSUE TITLE
책 164페이지 오타

### ISSUE THREAD

**Issue by Cruising0904** [han41858/Angular-Development-with-TypeScript#46]
코드 3.21 두번째 줄
import { Product, ProductService } from '../../services/product.service';
책에는 product-service 로 되어 있습니다. 수정 부탁드리겠습니다

**Comment by han41858** [comment]
안녕하세요. 한장현입니다.

말씀하신 대로 `product.service`가 맞습니다 ㅠㅠ

제보해주셔서 고맙습니다!!
