### ISSUE TITLE
오타?

### ISSUE THREAD

**Issue by GimYoungPhil** [han41858/Angular-Development-with-TypeScript#7]
p.187
providers는 프로바이더를 등록하는 어노테이션 프로퍼티고, provide**r**는 개별 프로바이터에 사용하는 프로퍼티다.

providers는 프로바이더를 등록하는 어노테이션 프로퍼티고, **provide**는 개별 프로바이터에 사용하는 프로퍼티다.

내용이 맞나요?

**Comment by han41858** [comment]
개별 프로바이더는 provide로 쓰는 것이 맞습니다 ㅎ

꼼꼼하게 봐주시니 고마울 따름입니다 ㅎㅎㅎ

지적 감사합니다!!
