### ISSUE TITLE
오타?

### ISSUE THREAD

**Issue by GimYoungPhil** [han41858/Angular-Development-with-TypeScript#8]
p.212 가장 아래 문단

providers 프로퍼티를 viewProviders**를** 변경하면 되는데,

providers 프로퍼티를 viewProviders로(?) 변경하면 되는데,

문장이 어색한데 이런 의미인가요?

**Comment by han41858** [comment]
그 의도였는데 문장이 어색하네요 ㅎㅎㅎ
'로'로 바꾸는 것이 맞습니다

고맙습니다!!
