### ISSUE TITLE
책 난이도 문의

### ISSUE THREAD

**Issue by jinsangYoo** [han41858/Angular-Development-with-TypeScript#9]
저는 nodejs로 간단한 REST API 싸이트와 간단한 관리자 웹사이트를 만들어본 경험이있고
거기에 angular를 프론트엔드로 적용해볼 심산으로 책을 구매해서 보고 있습니다.

앞서 얘기 한 것과 같이 nodejs 웹서버에 angular 프레임웍을 적용하는게 가능한가요? ㅋㅋ
지금 부록B와 p.60 쯤 읽어 봤을 때는 
nodejs의 렌더링 엔진으로 ejb를 사용하고 있는데 도무지 어떻게 적용시켜넣을지 감이 안잡혀서요

걍 때리치고 앞버전의 angularjs나 볼까요? ㅋㅋㅋ

도와주세요 ㅋㅋ 
angular 소개 챕터는 앞서서 다른 책을 p.100 정도 읽었기에 망정이지 angular 처음 접하는 사람은 전혀 모르겠는데요? 각주 설명도 없고

예제에 라인넘버도 없어서 저자님께 코드관련해서 물어볼려면 더더욱 난감하네요

**Comment by GimYoungPhil** [comment]
책의 저자님이 답변 주시겠지만 조금 내용을 적어보겠습니다.

1. 우선 Angular 프레임워크에 포함된 기능이 많아서 내용이 많습니다. 또한 SystemJS, Webpack, ES6, TypeScript 등등 다른 부수적인 툴, 언어들도 알아야 합니다. 다른 프레임워크 React, Vue.js 또한 마찬가지입니다.

그렇지만 초보자들이 배우지 못하는 프레임워크도 아닙니다. 처음부터 모든 내용을 알려고 하며 골치가 아픕니다. 기본적인 부분들부터 이해하시고 나머지 부분은 이런부분이 있구나 정도 기억해 두고 실제 구현이 필요할 때는 다시 책이나, 문서를 보면서 만듭니다. 보통 책의 각 챕터마다 기본적인 부분 50%, 고급 기능 50% 정도로 보시면 됩니다. 그리고 각 챕터의 마지막 실습예제에서 사용하는 것이 기본기능이라 보시면 됩니다. 그렇기 때문에 실습은 직접 만들어 보아야 합니다.

SystemJS, Webpack, ES6, TypeScript 이런 부수적인 것들도 하나하나 내용이 많으니깐 책에서 설명하는 정도만 파악해 두셨다가 실제 필요할 때마다 문서를 찾아서 배우시기 바랍니다.

2. node.js 로는 기본의 개발 방식처럼 프론트+서버(node.js)가 결합되는 형태로도 개발 가능하고, 
프론트(Angular, React, Vue)와 백엔드(node.js REST API)가 분리되는 형태로 개발도 가능합니다.

3. 처음 배우신다면 전 버전 보다는 새로운 버전을 추천합니다.

**Comment by han41858** [comment]
질문하신 내용에 답부터 먼저 드리자면,
Node.js에 Angular 프레임워크를 적용하는 것은 당연히 가능합니다.

그리고 AngularJS를 보는 것보다는 Angular를 보는 것을 추천합니다.


아시다시피 요즘 웹 개발, 특히 프론트엔드 개발은 공부해야 할 것이 참 많습니다.
Angular만 해도 윗분이 언급하신 대로 TypeScript나 ES6, Webpack에 대한 부분을 알아야 제대로 개발할 수 있죠. 게다가 Angular는 React나 Vue.js와 다르게 프론트엔드 전 영역을 커버하고 있어서 제공하는 기능도 많습니다.

제 책에서 Angular 모든 내용을 다루지는 않았지만, 책에서 다룬 내용보다 더 깊이 고민해야 하는 내용도 많습니다.
책을 읽으면서 모든 내용을 한 번에 이해하는 것도 좋지만, 윗분이 말씀하신대로 쭉 읽으면서 '이런 내용이 있구나'를 느끼고, 필요한 부분이 있을 때 자세히 찾아보는 방식이 좋다는 점은 동의합니다.
@GimYoungPhil 님께서 이미 좋은 답변을 달아주셨네요 ㅎ

코드 줄번호는 없지만 페이지와 해당 부분을 언급하시면 금방 찾아서 도움을 드릴 수 있습니다^^

참고로, pug나 ejb와 같은 템플릿 엔진으로 Angular를 제공하는 방법도 있지만, Angular에서는 프론트엔드만 따로 개발하고 Angular CLI나 Webpack으로 번들링해서 정적 리소스로 제공하는 것을 권장합니다.
